[package]
name = "solve-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.25.0"
solana-program = "*"
spl-token = "*"
solve = { path="./solve/programs/solve", features = ["no-entrypoint"]}
chall = { path="../framework/chall/programs/chall", features = ["no-entrypoint"]}
spl-associated-token-account = "1.0.5"
