[package]
name = "solve"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solve"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[profile.release]
overflow-checks = true
opt-level = 3
incremental = false
codegen-units = 1

[dependencies]
spl-associated-token-account = "1.0.5"
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
chall = { path = "../../../../framework/chall/programs/chall", features = ["cpi"]}
